eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Wirley Almeida  
  mail: wirley.s.almeida@gmail.com
server:
  port: ${PORT:9999}
message: Generic
